### PR TITLE
Bump yargs

### PR DESCRIPTION
**Pull request by roderickhsiao**
https://github.com/bcoe/yargs/blob/master/CHANGELOG.md 

we are using 

``` js
const yargs = require("yargs")
    .options("config", {});
```

shouldn't breaking anything,

run `node --harmony run-tests` pass the unit tests

### CODE REVIEW

**Comment by cbas** [comment]
LGTM. Can this tiny fix please be merged and published? Helps resolve a lot of downstream problems.
/cc @olov

**Comment by olov** [comment]
@cbas I was not aware of any problems with the old version in use - what are those? Thanks.

**Comment by cbas** [comment]
I'm dealing with warnings due to an invalid SPDX identifier in `package.json` of older yargs versions. e.g. yargs@1.3.2 specifies `"license": "MIT/X11",` instead of the correct `MIT`. This has been fixed since and a version bump in `defs` would eliminate the warnings.

Ref: [yargs@1.3.2 w/ invalid license field](https://github.com/bcoe/yargs/blob/b8d34725482e5821a3cc809c0df71378f282f526/package.json#L49)

**Comment by sebdeckers** [comment]
:bow: ty

**Pull request merged**
